### ISSUE TITLE
Implement game panel and structure for background

### ISSUE THREAD

**Issue by lucaszetterberg** [lucaszetterberg/ZigmaRunner#3]
*By structure for background it implies that the background does not have to be chosen already but should be able to be implemented easily, i.e. all the coding should be done.

**Comment by lucaszetterberg** [comment]
Done

**Comment by DilanSaleh** [comment]
Not done yet

**Comment by lucaszetterberg** [comment]
Task a bit to complicated for week one, moving it to week 2
