### ISSUE TITLE
Project Description & Documentation

### ISSUE THREAD

**Issue by AxelAxhag** [lucaszetterberg/ZigmaRunner#50]
It does a well job of describing the general project direction as well as having a good dependencies list. However, it lacks instruction on how to run the program and also how the user is supposed to interact with it. For example, you can't run the main script in a terminal. In order for it to run you have to run it in a code editor. 

In general the description and documentation is enough for a user to figure out on its own, but there could be a few hoops that stand in the way of the program actually being run by the user.  

We have realised through looking at your READMe.md file that we lack Authors category as well as a libraries list.

Well done, fix these issues and it should be more than enough according to us :)

**Comment by lucaszetterberg** [comment]
Thank you for the feedback, we hadn't discovered that bug yet! We have now added code that enables the user to run the game from the terminal.
