### ISSUE TITLE
Commit Log messages

### ISSUE THREAD

**Issue by AxelAxhag** [lucaszetterberg/ZigmaRunner#51]
The vast majority of the commit logs are both concise and informing which is exactly what commit messages should be like. There are of course some minor issues with very few of the commit logs, such as 334451724fcd779918e3f4c955fe6e2f7e87a659 where it's named "fix". On top of that the commits are also documented for every small fix which is exactly right.

There are few suggestions that we could make in order to make the commit logs better. One might be to make those commits which only say "fix" but these were really few. 

Where we lacked ourselves was in making the commits big where we had larger portions of code being committed, so this is definitely a learning experience for us.

**Comment by lucaszetterberg** [comment]
Thank you for your feedback! :) Glad you also recieved a positive outcome of reviewing our repo!
