### ISSUE TITLE
Milestones and Features in Issue Tracker

### ISSUE THREAD

**Issue by AxelAxhag** [lucaszetterberg/ZigmaRunner#52]
The repo does a very good job of making milestones structured using issues that are attached to that specific milestone. We also appreciate that the milestones are divided into different weeks making it a lot easier to track the progress of the project. 

There really aren't any suggestions that can be made. The milestones were used to their full potential and in a professional way. Perhaps milestones could be closed after they're finished but it's a bit of a nitpick.

What we can take from this is that it's smart to divide the milestones into weeks instead of features to be added.

Great job!

**Comment by lucaszetterberg** [comment]
Thank you for your feedback! :)
